name: Build and Deploy Foster Makhana Website

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    # Manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint || true

      - name: Build
        run: npm run build
        env:
          # Add any environment variables needed for build
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL || 'https://fostermakhana.com' }}

      - name: Run Tests
        run: npm test || true

      # Cache Next.js build output
      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      # Deploy to Vercel (if you're using Vercel)
      - name: Deploy to Vercel
        if: github.event_name != 'pull_request'
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--prod'

      # Alternative: Deploy to GitHub Pages
      # Uncomment this section if you're using GitHub Pages instead of Vercel
      # - name: Deploy to GitHub Pages
      #   if: github.event_name != 'pull_request'
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: out # Use "out" if you've configured Next.js for static export
      #     branch: gh-pages
